class Billing_locators:
   find_element_XPATH_myAccount='//span[text()="My account"]'
   find_element_XPATH_email='//input[@name="email"]'
   find_element_XPATH_password_send_keys='//input[@id="reg_password"]'
   find_element_XPATH_button='//button[@name="register"]'
   find_element_LINK_TEXT_adresses='Addresses'
   find_element_LINK_TEXT_edit = 'Edit'
   find_element_ID_send_keys_name='billing_first_name'
   find_element_ID_send_keys_lastname='billing_last_name'
   find_element_ID_billing_country='billing_country'
   find_element_ID_billing_address1_send_keys='billing_address_1'
   find_element_ID_billing_postcode_send_keys='billing_postcode'
   find_element_ID_billing_city_send_keys='billing_city'
   find_element_ID_billing_phone_send_keys='billing_phone'
   find_element_XPATH_button_save_address='//button[@name="save_address"]'
   find_element_XPATH_woocommerce_message_button='//div[@class="woocommerce-message"]'
